services:
    db:
        image: mariadb:10.5
        environment:
            - MYSQL_ROOT_PASSWORD=yetirootsecret
            - MYSQL_DATABASE=yetiforce
            - MYSQL_USER=yeti
            - MYSQL_PASSWORD=yetidbsecret
            - TZ=Europe/Warsaw
        healthcheck:
            test: "/usr/bin/mysql --user=yeti --password=yetidbsecret --execute \"SHOW DATABASES;\""
            interval: 10s
            timeout: 1s
            retries: 5
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
            - ./configs/db:/etc/mysql/mariadb.conf.d
        restart: unless-stopped

    apirestful:
               build:
                   context: ./src/apirestful
                   args:
                       - IMAGE_NAME=apirestful
                       - IMAGE_TAG=v1
               ports:
                   - 8000:80

    cms:
        build:
            context: ./src
            args:
                BUILD_INSTALL_MODE: PROD
                BUILD_SSL: "ON"
                BUILD_TZ: "Europe/Warsaw"
        # image: ghcr.io/dotsystemsspzoo/pdss:tst
        image: pmc/cms:v10
        environment:
            - TZ=EST5EDT
            - GUI_MODE=true
        ports:
            - 443:443
        volumes:
            - ./configs/cms/logo:/var/www/html/public_html/layouts/resources/Logo/logo
            - ./configs/cms/registration.php:/var/www/html/app_data/registration.php
            - ./logs-archive:/logs
            - ./logs:/var/www/html/cache/logs
            - ./storage:/var/www/html/storage
            - ./configs/cms/config:/var/www/html/config
            - ./configs/cms/php/php-fpm-pool.conf:/etc/php/7.4/fpm/pool.d/www.conf
            - ./configs/cms/php/yetiforce.ini:/etc/php/7.4/mods-available/yetiforce.ini
            - ./configs/cms/nginx/yetiforce.conf:/etc/nginx/yetiforce.conf
            - ./configs/cms/certificate/FullChain-pmc01-cert.pem:/etc/nginx/ssl/fullchain.pem
            - ./configs/cms/certificate/pmc01-key.pem:/etc/nginx/ssl/privkey.pem
            - ./cache/vtlib:/var/www/html/cache/vtlib
        depends_on:
            - db
        stop_grace_period: 15s
        hostname: cms
    



