TYPE=VIEW
query=select concat(`u`.`first_name`,\' \',`u`.`last_name`) AS `user_name`,`b`.`changedon` AS `changed_on`,case `b`.`status` when 0 then \'Updated\' when 1 then \'Deleted\' when 2 then \'Created\' when 3 then \'Activated\' when 4 then \'Linked\' when 6 then \'Unlinked\' when 6 then \'Converted\' when 7 then \'Displayed\' when 8 then \'Archived\' when 9 then \'Removed\' when 10 then \'Merged (edited)\' when 11 then \'Merged (deleted)\' when 12 then \'Merged (unlinked)\' when 13 then \'Merged (linked)\' when 14 then \'Unhid\' else \'???\' end AS `operation`,`t`.`tablabel` AS `module_label`,case `t`.`tablabel` when \'Comments\' then (select `l`.`label` from (`yetiforce`.`u_yf_crmentity_label` `l` join `yetiforce`.`vtiger_modcomments` `c` on(`l`.`crmid` = `c`.`related_to`)) where `c`.`modcommentsid` = `b`.`crmid`) else (select `l`.`label` from `yetiforce`.`u_yf_crmentity_label` `l` where `l`.`crmid` = `b`.`crmid`) end AS `item_label`,case when `b`.`status` = 4 then (select `tl`.`tablabel` from (`yetiforce`.`vtiger_tab` `tl` join `yetiforce`.`vtiger_modtracker_relations` `r` on(`tl`.`name` = `r`.`targetmodule`)) where `r`.`id` = `b`.`id`) else `df`.`fieldlabel` end AS `field_label`,case when `b`.`status` = 4 then (select `dl`.`label` from (`yetiforce`.`u_yf_crmentity_label` `dl` join `yetiforce`.`vtiger_modtracker_relations` `r` on(`dl`.`crmid` = `r`.`targetid`)) where `r`.`id` = `b`.`id`) when `df`.`uitype` = 10 then (select `dl`.`label` from `yetiforce`.`u_yf_crmentity_label` `dl` where `dl`.`crmid` = `d`.`postvalue`) when `df`.`uitype` in (52,53) then (select concat(`du`.`first_name`,\' \',`du`.`last_name`) from `yetiforce`.`vtiger_users` `du` where `du`.`id` = `d`.`postvalue`) else `d`.`postvalue` end AS `new_value`,`b`.`crmid` AS `crmid`,`b`.`id` AS `id` from ((((`yetiforce`.`vtiger_modtracker_basic` `b` join `yetiforce`.`vtiger_users` `u` on(`u`.`id` = `b`.`whodid`)) join `yetiforce`.`vtiger_tab` `t` on(`t`.`name` = `b`.`module`)) left join `yetiforce`.`vtiger_modtracker_detail` `d` on(`d`.`id` = `b`.`id`)) left join `yetiforce`.`vtiger_field` `df` on(`df`.`tabid` = `t`.`tabid` and `df`.`fieldname` = `d`.`fieldname`)) where 1 = 1 and `u`.`user_name`  not like \'admin%\' and `u`.`user_name` <> \'---\' and (`t`.`tablabel` <> \'Comments\' or `df`.`fieldlabel` in (\'Comment\',\'ReasonToEdit\')) order by `b`.`id`
md5=e27330c9aa90ec2549cb1387dea9582d
updatable=0
algorithm=0
definer_user=yeti
definer_host=%
suid=2
with_check_option=0
timestamp=2023-06-06 10:34:02
create-version=2
source=SELECT \n  -- basic info \n	CONCAT(u.first_name, \' \', u.last_name) AS user_name, b.changedon AS changed_on, \n	case b.status \n		when 0 then \'Updated\' when 1 then \'Deleted\' when 2 then \'Created\' when 3 then \'Activated\' when 4 then \'Linked\'\n		when 6 then \'Unlinked\' when 6 then \'Converted\' when 7 then \'Displayed\' when 8 then \'Archived\' when 9 then \'Removed\' \n		when 10 then \'Merged (edited)\' when 11 then \'Merged (deleted)\' when 12 then \'Merged (unlinked)\' when 13 then \'Merged (linked)\' \n		when 14 then \'Unhid\' ELSE \'???\'\n	 END AS operation,\n	t.tablabel AS module_label, \n	( case tablabel \n		when \'Comments\' then ( SELECT l.label FROM u_yf_crmentity_label l JOIN vtiger_modcomments c ON ( l.crmid = c.related_to ) WHERE c.modcommentsid = b.crmid )\n		ELSE ( SELECT l.label FROM u_yf_crmentity_label l WHERE l.crmid = b.crmid ) \n	  END ) AS item_label, \n  -- details\n	( case \n		when b.status = 4 then ( SELECT tl.tablabel FROM vtiger_tab tl JOIN vtiger_modtracker_relations r ON ( tl.name = r.targetmodule ) WHERE r.id = b.id )\n		ELSE df.fieldlabel\n		END ) AS field_label,\n	( case \n		when b.status = 4 then (SELECT dl.label FROM u_yf_crmentity_label dl JOIN vtiger_modtracker_relations r ON ( dl.crmid = r.targetid ) WHERE r.id = b.id )\n		when df.uitype IN (10) then (SELECT dl.label FROM u_yf_crmentity_label dl WHERE dl.crmid = d.postvalue ) \n		when df.uitype IN (52, 53) then (SELECT CONCAT(du.first_name, \' \', du.last_name) FROM vtiger_users du WHERE du.id = d.postvalue ) \n		ELSE postvalue \n	  END ) AS new_value,\n  -- technical data\n	b.crmid, b.id\n	-- , b.*\n	-- , u.*\nFROM vtiger_modtracker_basic b\n	JOIN vtiger_users u ON ( u.id = b.whodid )\n	JOIN vtiger_tab t ON ( t.name = b.module )\n	LEFT OUTER JOIN vtiger_modtracker_detail d ON ( d.id = b.id )\n	LEFT OUTER JOIN vtiger_field df ON ( df.tabid = t.tabid AND df.fieldname = d.fieldname )\nWHERE 1=1\n	AND u.user_name NOT LIKE \'admin%\' AND u.user_name <> \'---\'\n 	AND NOT ( t.tablabel = \'Comments\' AND df.fieldlabel NOT IN ( \'Comment\', \'ReasonToEdit\' ) )\n	-- AND u.last_name = \'Gonzalez\' AND u.first_name = \'Robert\'\n	-- AND u.last_name LIKE \'Flore%\'\n	-- AND module = \'Documents\'\n	-- AND DATE(changedon) = DATE(\'2023-5-29\')\nORDER BY b.id
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select concat(`u`.`first_name`,\' \',`u`.`last_name`) AS `user_name`,`b`.`changedon` AS `changed_on`,case `b`.`status` when 0 then \'Updated\' when 1 then \'Deleted\' when 2 then \'Created\' when 3 then \'Activated\' when 4 then \'Linked\' when 6 then \'Unlinked\' when 6 then \'Converted\' when 7 then \'Displayed\' when 8 then \'Archived\' when 9 then \'Removed\' when 10 then \'Merged (edited)\' when 11 then \'Merged (deleted)\' when 12 then \'Merged (unlinked)\' when 13 then \'Merged (linked)\' when 14 then \'Unhid\' else \'???\' end AS `operation`,`t`.`tablabel` AS `module_label`,case `t`.`tablabel` when \'Comments\' then (select `l`.`label` from (`yetiforce`.`u_yf_crmentity_label` `l` join `yetiforce`.`vtiger_modcomments` `c` on(`l`.`crmid` = `c`.`related_to`)) where `c`.`modcommentsid` = `b`.`crmid`) else (select `l`.`label` from `yetiforce`.`u_yf_crmentity_label` `l` where `l`.`crmid` = `b`.`crmid`) end AS `item_label`,case when `b`.`status` = 4 then (select `tl`.`tablabel` from (`yetiforce`.`vtiger_tab` `tl` join `yetiforce`.`vtiger_modtracker_relations` `r` on(`tl`.`name` = `r`.`targetmodule`)) where `r`.`id` = `b`.`id`) else `df`.`fieldlabel` end AS `field_label`,case when `b`.`status` = 4 then (select `dl`.`label` from (`yetiforce`.`u_yf_crmentity_label` `dl` join `yetiforce`.`vtiger_modtracker_relations` `r` on(`dl`.`crmid` = `r`.`targetid`)) where `r`.`id` = `b`.`id`) when `df`.`uitype` = 10 then (select `dl`.`label` from `yetiforce`.`u_yf_crmentity_label` `dl` where `dl`.`crmid` = `d`.`postvalue`) when `df`.`uitype` in (52,53) then (select concat(`du`.`first_name`,\' \',`du`.`last_name`) from `yetiforce`.`vtiger_users` `du` where `du`.`id` = `d`.`postvalue`) else `d`.`postvalue` end AS `new_value`,`b`.`crmid` AS `crmid`,`b`.`id` AS `id` from ((((`yetiforce`.`vtiger_modtracker_basic` `b` join `yetiforce`.`vtiger_users` `u` on(`u`.`id` = `b`.`whodid`)) join `yetiforce`.`vtiger_tab` `t` on(`t`.`name` = `b`.`module`)) left join `yetiforce`.`vtiger_modtracker_detail` `d` on(`d`.`id` = `b`.`id`)) left join `yetiforce`.`vtiger_field` `df` on(`df`.`tabid` = `t`.`tabid` and `df`.`fieldname` = `d`.`fieldname`)) where 1 = 1 and `u`.`user_name`  not like \'admin%\' and `u`.`user_name` <> \'---\' and (`t`.`tablabel` <> \'Comments\' or `df`.`fieldlabel` in (\'Comment\',\'ReasonToEdit\')) order by `b`.`id`
mariadb-version=100513
