TYPE=VIEW
query=select `e`.`crmid` AS `claimcollection`,`e`.`createdtime` AS `createdtime`,`d`.`claimcollectionsid` AS `claimcollectionsid`,`d`.`claim_collection_name` AS `claim_collection_name`,`d`.`number` AS `number`,`d`.`assigned_value` AS `assigned_value`,`d`.`assigned_below_hurdle` AS `assigned_below_hurdle`,`d`.`assigned_refundable_reserve` AS `assigned_refundable_reserve`,`d`.`assigned_limit_reserve` AS `assigned_limit_reserve`,`d`.`disbursed_date` AS `disbursed_date`,`d`.`collection` AS `collection`,`d`.`portfolio` AS `portfolio`,`d`.`claim` AS `claim` from ((select `yetiforce`.`u_yf_claimcollections`.`claimcollectionsid` AS `claimcollectionsid`,`yetiforce`.`u_yf_claimcollections`.`claim_collection_name` AS `claim_collection_name`,`yetiforce`.`u_yf_claimcollections`.`number` AS `number`,`yetiforce`.`u_yf_claimcollections`.`assigned_value` AS `assigned_value`,`yetiforce`.`u_yf_claimcollections`.`assigned_below_hurdle` AS `assigned_below_hurdle`,`yetiforce`.`u_yf_claimcollections`.`assigned_refundable_reserve` AS `assigned_refundable_reserve`,`yetiforce`.`u_yf_claimcollections`.`assigned_limit_reserve` AS `assigned_limit_reserve`,`yetiforce`.`u_yf_claimcollections`.`disbursed_date` AS `disbursed_date`,`yetiforce`.`u_yf_claimcollections`.`collection` AS `collection`,`yetiforce`.`u_yf_claimcollections`.`portfolio` AS `portfolio`,`yetiforce`.`u_yf_claimcollections`.`claim` AS `claim` from (`yetiforce`.`u_yf_claimcollections` join `yetiforce`.`u_yf_claimcollectionscf` on(`yetiforce`.`u_yf_claimcollections`.`claimcollectionsid` = `yetiforce`.`u_yf_claimcollectionscf`.`claimcollectionsid`))) `d` join `yetiforce`.`vtiger_crmentity` `e` on(`e`.`crmid` = `d`.`claimcollectionsid`)) where `e`.`deleted` = 0
md5=b1331fbb2d019bcfeba4e85fd1dc7b01
updatable=1
algorithm=0
definer_user=yeti
definer_host=%
suid=2
with_check_option=0
timestamp=2022-11-24 13:00:43
create-version=2
source=SELECT e.crmid AS claimcollection, e.createdtime,\n	d.*\nFROM (\n		SELECT *\n		FROM u_yf_claimcollections NATURAL JOIN u_yf_claimcollectionscf\n		) d\n	JOIN vtiger_crmentity e ON ( e.crmid = d.claimcollectionsid )\nWHERE e.deleted = 0
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `e`.`crmid` AS `claimcollection`,`e`.`createdtime` AS `createdtime`,`d`.`claimcollectionsid` AS `claimcollectionsid`,`d`.`claim_collection_name` AS `claim_collection_name`,`d`.`number` AS `number`,`d`.`assigned_value` AS `assigned_value`,`d`.`assigned_below_hurdle` AS `assigned_below_hurdle`,`d`.`assigned_refundable_reserve` AS `assigned_refundable_reserve`,`d`.`assigned_limit_reserve` AS `assigned_limit_reserve`,`d`.`disbursed_date` AS `disbursed_date`,`d`.`collection` AS `collection`,`d`.`portfolio` AS `portfolio`,`d`.`claim` AS `claim` from ((select `yetiforce`.`u_yf_claimcollections`.`claimcollectionsid` AS `claimcollectionsid`,`yetiforce`.`u_yf_claimcollections`.`claim_collection_name` AS `claim_collection_name`,`yetiforce`.`u_yf_claimcollections`.`number` AS `number`,`yetiforce`.`u_yf_claimcollections`.`assigned_value` AS `assigned_value`,`yetiforce`.`u_yf_claimcollections`.`assigned_below_hurdle` AS `assigned_below_hurdle`,`yetiforce`.`u_yf_claimcollections`.`assigned_refundable_reserve` AS `assigned_refundable_reserve`,`yetiforce`.`u_yf_claimcollections`.`assigned_limit_reserve` AS `assigned_limit_reserve`,`yetiforce`.`u_yf_claimcollections`.`disbursed_date` AS `disbursed_date`,`yetiforce`.`u_yf_claimcollections`.`collection` AS `collection`,`yetiforce`.`u_yf_claimcollections`.`portfolio` AS `portfolio`,`yetiforce`.`u_yf_claimcollections`.`claim` AS `claim` from (`yetiforce`.`u_yf_claimcollections` join `yetiforce`.`u_yf_claimcollectionscf` on(`yetiforce`.`u_yf_claimcollections`.`claimcollectionsid` = `yetiforce`.`u_yf_claimcollectionscf`.`claimcollectionsid`))) `d` join `yetiforce`.`vtiger_crmentity` `e` on(`e`.`crmid` = `d`.`claimcollectionsid`)) where `e`.`deleted` = 0
mariadb-version=100513
