TYPE=VIEW
query=select `e`.`crmid` AS `investor`,`e`.`createdtime` AS `createdtime`,`d`.`investorsid` AS `investorsid`,`d`.`investor_name` AS `investor_name`,`d`.`number` AS `number`,`d`.`is_active` AS `is_active`,`d`.`street` AS `street`,`d`.`www` AS `www`,`d`.`email_addresses` AS `email_addresses`,`d`.`zip` AS `zip`,`d`.`city` AS `city`,`d`.`state` AS `state`,`d`.`contact_person` AS `contact_person`,`d`.`e_mail` AS `e_mail`,`d`.`phone` AS `phone`,`d`.`phone_extra` AS `phone_extra` from ((select `yetiforce`.`u_yf_investors`.`investorsid` AS `investorsid`,`yetiforce`.`u_yf_investors`.`investor_name` AS `investor_name`,`yetiforce`.`u_yf_investors`.`number` AS `number`,`yetiforce`.`u_yf_investors`.`is_active` AS `is_active`,`yetiforce`.`u_yf_investors`.`street` AS `street`,`yetiforce`.`u_yf_investors`.`www` AS `www`,`yetiforce`.`u_yf_investors`.`email_addresses` AS `email_addresses`,`yetiforce`.`u_yf_investorscf`.`zip` AS `zip`,`yetiforce`.`u_yf_investorscf`.`city` AS `city`,`yetiforce`.`u_yf_investorscf`.`state` AS `state`,`yetiforce`.`u_yf_investorscf`.`contact_person` AS `contact_person`,`yetiforce`.`u_yf_investorscf`.`e_mail` AS `e_mail`,`yetiforce`.`u_yf_investorscf`.`phone` AS `phone`,`yetiforce`.`u_yf_investorscf`.`phone_extra` AS `phone_extra` from (`yetiforce`.`u_yf_investors` join `yetiforce`.`u_yf_investorscf` on(`yetiforce`.`u_yf_investors`.`investorsid` = `yetiforce`.`u_yf_investorscf`.`investorsid`))) `d` join `yetiforce`.`vtiger_crmentity` `e` on(`e`.`crmid` = `d`.`investorsid`)) where `e`.`deleted` = 0
md5=5e5cdf27574dbbab12fff559ba234eb0
updatable=1
algorithm=0
definer_user=yeti
definer_host=%
suid=2
with_check_option=0
timestamp=2022-11-24 13:00:43
create-version=2
source=SELECT e.crmid AS investor, e.createdtime,\n	d.*\nFROM (\n		SELECT *\n		FROM u_yf_investors NATURAL JOIN u_yf_investorscf\n		) d\n	JOIN vtiger_crmentity e ON ( e.crmid = d.investorsid )\nWHERE e.deleted = 0
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `e`.`crmid` AS `investor`,`e`.`createdtime` AS `createdtime`,`d`.`investorsid` AS `investorsid`,`d`.`investor_name` AS `investor_name`,`d`.`number` AS `number`,`d`.`is_active` AS `is_active`,`d`.`street` AS `street`,`d`.`www` AS `www`,`d`.`email_addresses` AS `email_addresses`,`d`.`zip` AS `zip`,`d`.`city` AS `city`,`d`.`state` AS `state`,`d`.`contact_person` AS `contact_person`,`d`.`e_mail` AS `e_mail`,`d`.`phone` AS `phone`,`d`.`phone_extra` AS `phone_extra` from ((select `yetiforce`.`u_yf_investors`.`investorsid` AS `investorsid`,`yetiforce`.`u_yf_investors`.`investor_name` AS `investor_name`,`yetiforce`.`u_yf_investors`.`number` AS `number`,`yetiforce`.`u_yf_investors`.`is_active` AS `is_active`,`yetiforce`.`u_yf_investors`.`street` AS `street`,`yetiforce`.`u_yf_investors`.`www` AS `www`,`yetiforce`.`u_yf_investors`.`email_addresses` AS `email_addresses`,`yetiforce`.`u_yf_investorscf`.`zip` AS `zip`,`yetiforce`.`u_yf_investorscf`.`city` AS `city`,`yetiforce`.`u_yf_investorscf`.`state` AS `state`,`yetiforce`.`u_yf_investorscf`.`contact_person` AS `contact_person`,`yetiforce`.`u_yf_investorscf`.`e_mail` AS `e_mail`,`yetiforce`.`u_yf_investorscf`.`phone` AS `phone`,`yetiforce`.`u_yf_investorscf`.`phone_extra` AS `phone_extra` from (`yetiforce`.`u_yf_investors` join `yetiforce`.`u_yf_investorscf` on(`yetiforce`.`u_yf_investors`.`investorsid` = `yetiforce`.`u_yf_investorscf`.`investorsid`))) `d` join `yetiforce`.`vtiger_crmentity` `e` on(`e`.`crmid` = `d`.`investorsid`)) where `e`.`deleted` = 0
mariadb-version=100513
