TYPE=VIEW
query=select `e`.`crmid` AS `outside_case`,`e`.`createdtime` AS `createdtime`,`d`.`outsidecasesid` AS `outsidecasesid`,`d`.`outside_case_id` AS `outside_case_id`,`d`.`number` AS `number`,`d`.`claim_number` AS `claim_number`,`d`.`lock_automation` AS `lock_automation`,`d`.`total_bill_amount` AS `total_bill_amount`,`d`.`pmc_collections_limit` AS `pmc_collections_limit`,`d`.`total_collections` AS `total_collections`,`d`.`total_balance` AS `total_balance`,`d`.`litigation_status` AS `litigation_status`,`d`.`litigation_status_other` AS `litigation_status_other`,`d`.`note` AS `note`,`d`.`insured` AS `insured`,`d`.`policy_number` AS `policy_number`,`d`.`insurance_company` AS `insurance_company`,`d`.`type_of_claim` AS `type_of_claim`,`d`.`provider` AS `provider`,`d`.`outside_case_number` AS `outside_case_number`,`d`.`date_of_loss` AS `date_of_loss`,`d`.`first_notice_of_loss` AS `first_notice_of_loss`,`d`.`service_types` AS `service_types`,`d`.`types_of_services` AS `types_of_services` from ((select `yetiforce`.`u_yf_outsidecases`.`outsidecasesid` AS `outsidecasesid`,`yetiforce`.`u_yf_outsidecases`.`outside_case_id` AS `outside_case_id`,`yetiforce`.`u_yf_outsidecases`.`number` AS `number`,`yetiforce`.`u_yf_outsidecases`.`claim_number` AS `claim_number`,`yetiforce`.`u_yf_outsidecases`.`lock_automation` AS `lock_automation`,`yetiforce`.`u_yf_outsidecases`.`total_bill_amount` AS `total_bill_amount`,`yetiforce`.`u_yf_outsidecases`.`pmc_collections_limit` AS `pmc_collections_limit`,`yetiforce`.`u_yf_outsidecases`.`total_collections` AS `total_collections`,`yetiforce`.`u_yf_outsidecases`.`total_balance` AS `total_balance`,`yetiforce`.`u_yf_outsidecases`.`litigation_status` AS `litigation_status`,`yetiforce`.`u_yf_outsidecases`.`litigation_status_other` AS `litigation_status_other`,`yetiforce`.`u_yf_outsidecases`.`note` AS `note`,`yetiforce`.`u_yf_outsidecases`.`insured` AS `insured`,`yetiforce`.`u_yf_outsidecases`.`policy_number` AS `policy_number`,`yetiforce`.`u_yf_outsidecases`.`insurance_company` AS `insurance_company`,`yetiforce`.`u_yf_outsidecases`.`type_of_claim` AS `type_of_claim`,`yetiforce`.`u_yf_outsidecases`.`provider` AS `provider`,`yetiforce`.`u_yf_outsidecases`.`outside_case_number` AS `outside_case_number`,`yetiforce`.`u_yf_outsidecases`.`date_of_loss` AS `date_of_loss`,`yetiforce`.`u_yf_outsidecases`.`first_notice_of_loss` AS `first_notice_of_loss`,`yetiforce`.`u_yf_outsidecases`.`service_types` AS `service_types`,`yetiforce`.`u_yf_outsidecases`.`types_of_services` AS `types_of_services` from (`yetiforce`.`u_yf_outsidecases` join `yetiforce`.`u_yf_outsidecasescf` on(`yetiforce`.`u_yf_outsidecases`.`outsidecasesid` = `yetiforce`.`u_yf_outsidecasescf`.`outsidecasesid`))) `d` join `yetiforce`.`vtiger_crmentity` `e` on(`e`.`crmid` = `d`.`outsidecasesid`)) where `e`.`deleted` = 0
md5=02dd16d807979e1dd3973d1d92ecd87b
updatable=1
algorithm=0
definer_user=yeti
definer_host=%
suid=2
with_check_option=0
timestamp=2022-11-24 13:00:44
create-version=2
source=SELECT e.crmid AS outside_case, e.createdtime,\n	d.*\nFROM (\n		SELECT *\n		FROM u_yf_outsidecases NATURAL JOIN u_yf_outsidecasescf\n		) d\n	JOIN vtiger_crmentity e ON ( e.crmid = d.outsidecasesid )\nWHERE e.deleted = 0
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `e`.`crmid` AS `outside_case`,`e`.`createdtime` AS `createdtime`,`d`.`outsidecasesid` AS `outsidecasesid`,`d`.`outside_case_id` AS `outside_case_id`,`d`.`number` AS `number`,`d`.`claim_number` AS `claim_number`,`d`.`lock_automation` AS `lock_automation`,`d`.`total_bill_amount` AS `total_bill_amount`,`d`.`pmc_collections_limit` AS `pmc_collections_limit`,`d`.`total_collections` AS `total_collections`,`d`.`total_balance` AS `total_balance`,`d`.`litigation_status` AS `litigation_status`,`d`.`litigation_status_other` AS `litigation_status_other`,`d`.`note` AS `note`,`d`.`insured` AS `insured`,`d`.`policy_number` AS `policy_number`,`d`.`insurance_company` AS `insurance_company`,`d`.`type_of_claim` AS `type_of_claim`,`d`.`provider` AS `provider`,`d`.`outside_case_number` AS `outside_case_number`,`d`.`date_of_loss` AS `date_of_loss`,`d`.`first_notice_of_loss` AS `first_notice_of_loss`,`d`.`service_types` AS `service_types`,`d`.`types_of_services` AS `types_of_services` from ((select `yetiforce`.`u_yf_outsidecases`.`outsidecasesid` AS `outsidecasesid`,`yetiforce`.`u_yf_outsidecases`.`outside_case_id` AS `outside_case_id`,`yetiforce`.`u_yf_outsidecases`.`number` AS `number`,`yetiforce`.`u_yf_outsidecases`.`claim_number` AS `claim_number`,`yetiforce`.`u_yf_outsidecases`.`lock_automation` AS `lock_automation`,`yetiforce`.`u_yf_outsidecases`.`total_bill_amount` AS `total_bill_amount`,`yetiforce`.`u_yf_outsidecases`.`pmc_collections_limit` AS `pmc_collections_limit`,`yetiforce`.`u_yf_outsidecases`.`total_collections` AS `total_collections`,`yetiforce`.`u_yf_outsidecases`.`total_balance` AS `total_balance`,`yetiforce`.`u_yf_outsidecases`.`litigation_status` AS `litigation_status`,`yetiforce`.`u_yf_outsidecases`.`litigation_status_other` AS `litigation_status_other`,`yetiforce`.`u_yf_outsidecases`.`note` AS `note`,`yetiforce`.`u_yf_outsidecases`.`insured` AS `insured`,`yetiforce`.`u_yf_outsidecases`.`policy_number` AS `policy_number`,`yetiforce`.`u_yf_outsidecases`.`insurance_company` AS `insurance_company`,`yetiforce`.`u_yf_outsidecases`.`type_of_claim` AS `type_of_claim`,`yetiforce`.`u_yf_outsidecases`.`provider` AS `provider`,`yetiforce`.`u_yf_outsidecases`.`outside_case_number` AS `outside_case_number`,`yetiforce`.`u_yf_outsidecases`.`date_of_loss` AS `date_of_loss`,`yetiforce`.`u_yf_outsidecases`.`first_notice_of_loss` AS `first_notice_of_loss`,`yetiforce`.`u_yf_outsidecases`.`service_types` AS `service_types`,`yetiforce`.`u_yf_outsidecases`.`types_of_services` AS `types_of_services` from (`yetiforce`.`u_yf_outsidecases` join `yetiforce`.`u_yf_outsidecasescf` on(`yetiforce`.`u_yf_outsidecases`.`outsidecasesid` = `yetiforce`.`u_yf_outsidecasescf`.`outsidecasesid`))) `d` join `yetiforce`.`vtiger_crmentity` `e` on(`e`.`crmid` = `d`.`outsidecasesid`)) where `e`.`deleted` = 0
mariadb-version=100513
